version: "3.1"

services:
  memcached:
    image: memcached:alpine
    container_name: demoproject-memcached

  mariadb:
    image: mariadb:10.4
    container_name: demoproject-mariadb
    env_file:
      - .env.mysql
    ports:
      - "8033:3306"

  webserver:
    image: nginx:alpine
    container_name: demoproject-webserver
    working_dir: /application
    volumes:
      - ./app:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php-fpm:
    build: ./php-fpm
    container_name: demoproject-php-fpm
    working_dir: /application
    env_file:
      - .env.symfony
    volumes:
      - ./app:/application
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
